package createspecv0_test

import (
	"os"
	"testing"

	createspecv0 "github.com/moby/moby/v2/internal/extpoints/createspec/v0"
	"gotest.tools/v3/assert"
	"gotest.tools/v3/golden"
)

// schemaFile is the point's published contract, checked in beside the Go types
// it is rendered from.
const schemaFile = "create_spec_hook.proto"

// TestSchemaMatchesContract keeps the published .proto in step with the Go
// contract it is rendered from.
//
// The daemon never reads this file -- the wire form is derived from the Go types
// -- so nothing would break at runtime if it went stale. It would break the
// people it is for: an extension author in another language generates stubs from
// it, and a schema that quietly stopped matching the contract would produce
// stubs that fail at the first call. So it is compared here rather than
// regenerated by a build step.
//
// Run `go test ./extpoints/createspec/v0/ -test.update` to rewrite it after an
// intentional contract change. Changing the wire form of a released point is not
// something to do lightly: adding a field is compatible, renaming or renumbering
// one is not.
func TestSchemaMatchesContract(t *testing.T) {
	got := createspecv0.Contract.Proto()

	if golden.FlagUpdate() {
		assert.NilError(t, os.WriteFile(schemaFile, []byte(got), 0o644))
		return
	}

	want, err := os.ReadFile(schemaFile)
	assert.NilError(t, err)
	assert.Equal(t, got, string(want),
		"%s is out of date with the Go contract; re-run with -test.update", schemaFile)
}
