// Code generated by pointgen. DO NOT EDIT.

package createspecv0

import (
	"context"

	"github.com/moby/moby/v2/internal/extensions/wire"
)

// Wire is the point's contract and both sides of its gRPC wiring, derived from
// [Hook] and its message types.
var Wire = wire.Bind(Point, "CreateSpecHook", func(c wire.Client) Hook {
	return client{c}
})

// client calls a provider of the point that lives in another process. It has to
// satisfy [Hook], so a method added to the point breaks the build here until
// this file is regenerated.
type client struct {
	wire.Client
}

func (c client) CreateSpec(ctx context.Context, req *SpecRequest) (*SpecAdjustment, error) {
	return wire.Call[SpecAdjustment](ctx, c.Client, "CreateSpec", req)
}

func (c client) Validate(ctx context.Context, req *SpecRequest) error {
	return wire.Do(ctx, c.Client, "Validate", req)
}
