// Code generated by pointgen. DO NOT EDIT.

package greeterv0

import (
	"context"

	"github.com/moby/moby/v2/internal/extensions/wire"
)

// Wire is the point's contract and both sides of its gRPC wiring, derived from
// [Greeter] and its message types.
var Wire = wire.Bind(Point, "Greeter", func(c wire.Client) Greeter {
	return client{c}
})

// client calls a provider of the point that lives in another process. It has to
// satisfy [Greeter], so a method added to the point breaks the build here until
// this file is regenerated.
type client struct {
	wire.Client
}

func (c client) Greet(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return wire.Call[HelloReply](ctx, c.Client, "Greet", req)
}
