// Code generated by pointgen. DO NOT EDIT.

package echov1

import (
	"context"

	"github.com/moby/moby/v2/internal/extensions/wire"
)

// Wire is the point's contract and both sides of its gRPC wiring, derived from
// [EchoServer] and its message types.
var Wire = wire.Bind(Point, "Echo", func(c wire.Client) EchoServer {
	return client{c}
})

// client calls a provider of the point that lives in another process. It has to
// satisfy [EchoServer], so a method added to the point breaks the build here until
// this file is regenerated.
type client struct {
	wire.Client
}

func (c client) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return wire.Call[EchoResponse](ctx, c.Client, "Echo", req)
}
