package wire_test

import (
	"reflect"
	"testing"

	"github.com/moby/moby/v2/internal/extensions/wire"
	protogen "github.com/moby/moby/v2/internal/extensions/wire/internal/golden"
	createspecv0 "github.com/moby/moby/v2/internal/extpoints/createspec/v0"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"gotest.tools/v3/assert"
	is "gotest.tools/v3/assert/cmp"
)

// createSpecContract derives the create-spec point's wire contract from its Go
// types, exactly as the runtime does.
func createSpecContract(t *testing.T) *wire.Contract {
	t.Helper()
	c, err := wire.NewContract(
		string(createspecv0.Point.ID()),
		"CreateSpecHook",
		[]wire.Method{
			{
				Name:     "CreateSpec",
				Request:  reflect.TypeOf(createspecv0.SpecRequest{}),
				Response: reflect.TypeOf(createspecv0.SpecAdjustment{}),
			},
			{
				Name:    "Validate",
				Request: reflect.TypeOf(createspecv0.SpecRequest{}),
			},
		},
	)
	assert.NilError(t, err)
	return c
}

// TestWireCompatibility is the load-bearing test for deriving the wire contract
// at runtime instead of generating it: the bytes this package produces from the
// Go contract types must be exactly what protoc-gen-go produces from the
// generated .proto for the same point, in both directions.
//
// It is checked against the real create-spec point rather than a fixture, so a
// change to the contract types, to the field-naming rules, or to the descriptor
// builder that would break an already-deployed extension fails here.
func TestWireCompatibility(t *testing.T) {
	c := createSpecContract(t)

	src := &createspecv0.SpecRequest{
		ContainerID: "9f2c1e4b7a03",
		Name:        "/eager_hopper",
		Spec:        []byte(`{"ociVersion":"1.0.2","process":{"terminal":false}}`),
		Labels:      map[string]string{"com.example.tier": "prod", "owner": "team-a"},
	}

	t.Run("derived bytes decode with generated type", func(t *testing.T) {
		data, err := c.Marshal(src)
		assert.NilError(t, err)

		var got protogen.SpecRequest
		assert.NilError(t, proto.Unmarshal(data, &got))

		assert.Check(t, is.Equal(got.GetContainerId(), src.ContainerID))
		assert.Check(t, is.Equal(got.GetName(), src.Name))
		assert.Check(t, is.Equal(string(got.GetSpec()), string(src.Spec)))
		assert.Check(t, is.DeepEqual(got.GetLabels(), src.Labels))
	})

	t.Run("generated bytes decode with derived contract", func(t *testing.T) {
		data, err := proto.Marshal(&protogen.SpecRequest{
			ContainerId: src.ContainerID,
			Name:        src.Name,
			Spec:        src.Spec,
			Labels:      src.Labels,
		})
		assert.NilError(t, err)

		var got createspecv0.SpecRequest
		assert.NilError(t, c.Unmarshal(data, &got))
		assert.Check(t, is.DeepEqual(got, *src))
	})

	t.Run("byte-for-byte identical encoding", func(t *testing.T) {
		// Deterministic marshalling is required for this comparison: protobuf map
		// ordering is otherwise unspecified, so a difference here would be noise
		// rather than an incompatibility.
		derived, err := c.ToDynamic(src)
		assert.NilError(t, err)
		a, err := proto.MarshalOptions{Deterministic: true}.Marshal(derived)
		assert.NilError(t, err)

		b, err := proto.MarshalOptions{Deterministic: true}.Marshal(&protogen.SpecRequest{
			ContainerId: src.ContainerID,
			Name:        src.Name,
			Spec:        src.Spec,
			Labels:      src.Labels,
		})
		assert.NilError(t, err)
		assert.DeepEqual(t, a, b)
	})
}

// TestDerivedDescriptorMatchesGenerated checks the derived descriptor against
// the one protoc produced, field by field. Matching bytes for one sample value
// is necessary but not sufficient -- a field the sample leaves zero could differ
// in number, name, or kind and still round-trip -- so the schema itself is
// compared.
func TestDerivedDescriptorMatchesGenerated(t *testing.T) {
	c := createSpecContract(t)

	for _, name := range []protoreflect.Name{"SpecRequest", "SpecAdjustment"} {
		t.Run(string(name), func(t *testing.T) {
			derived := c.File().Messages().ByName(name)
			assert.Assert(t, derived != nil, "derived descriptor missing %s", name)

			var generated protoreflect.MessageDescriptor
			switch name {
			case "SpecRequest":
				generated = (&protogen.SpecRequest{}).ProtoReflect().Descriptor()
			case "SpecAdjustment":
				generated = (&protogen.SpecAdjustment{}).ProtoReflect().Descriptor()
			}

			assert.Check(t, is.Equal(string(derived.FullName()), string(generated.FullName())))
			assert.Assert(t, is.Equal(derived.Fields().Len(), generated.Fields().Len()))

			for i := 0; i < generated.Fields().Len(); i++ {
				want := generated.Fields().Get(i)
				got := derived.Fields().ByNumber(want.Number())
				assert.Assert(t, got != nil, "derived %s missing field %d (%s)", name, want.Number(), want.Name())
				assert.Check(t, is.Equal(string(got.Name()), string(want.Name())), "field %d name", want.Number())
				assert.Check(t, is.Equal(got.Kind(), want.Kind()), "field %s kind", want.Name())
				assert.Check(t, is.Equal(got.IsList(), want.IsList()), "field %s list-ness", want.Name())
				assert.Check(t, is.Equal(got.IsMap(), want.IsMap()), "field %s map-ness", want.Name())
				if want.IsMap() {
					assert.Check(t, is.Equal(got.MapKey().Kind(), want.MapKey().Kind()), "field %s map key", want.Name())
					assert.Check(t, is.Equal(got.MapValue().Kind(), want.MapValue().Kind()), "field %s map value", want.Name())
				}
			}
		})
	}
}

// TestFullMethodMatchesGenerated checks that the gRPC path derived from the
// point id and service name is the one the generated client dials. If these
// diverge, a launched extension serves a method the daemon never calls.
func TestFullMethodMatchesGenerated(t *testing.T) {
	c := createSpecContract(t)
	assert.Check(t, is.Equal(c.FullService(), protogen.CreateSpecHook_ServiceDesc.ServiceName))
	for _, m := range protogen.CreateSpecHook_ServiceDesc.Methods {
		assert.Check(t, is.Equal(c.FullMethod(m.MethodName), "/"+c.FullService()+"/"+m.MethodName))
	}
}

// BenchmarkRoundTrip measures the per-call cost of deriving the wire form by
// reflection. It only applies to calls that cross the process boundary -- an
// in-process provider is a direct Go call and never reaches this code -- so it
// is compared against the gRPC round trip it is part of, not against a
// function call.
func BenchmarkRoundTrip(b *testing.B) {
	c, err := wire.NewContract(
		string(createspecv0.Point.ID()), "CreateSpecHook",
		[]wire.Method{{
			Name:     "CreateSpec",
			Request:  reflect.TypeOf(createspecv0.SpecRequest{}),
			Response: reflect.TypeOf(createspecv0.SpecAdjustment{}),
		}},
	)
	if err != nil {
		b.Fatal(err)
	}
	src := &createspecv0.SpecRequest{
		ContainerID: "9f2c1e4b7a03",
		Name:        "/eager_hopper",
		Spec:        make([]byte, 4096),
		Labels:      map[string]string{"a": "1", "b": "2"},
	}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		data, err := c.Marshal(src)
		if err != nil {
			b.Fatal(err)
		}
		var out createspecv0.SpecRequest
		if err := c.Unmarshal(data, &out); err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkRoundTripGenerated is the same round trip through the generated
// path -- convert the contract value to the protoc-generated struct, marshal,
// unmarshal, convert back -- so the cost of deriving the wire form at runtime
// can be read as a ratio rather than an absolute number. The conversions mirror
// what wire.gen.go emits.
func BenchmarkRoundTripGenerated(b *testing.B) {
	src := &createspecv0.SpecRequest{
		ContainerID: "9f2c1e4b7a03",
		Name:        "/eager_hopper",
		Spec:        make([]byte, 4096),
		Labels:      map[string]string{"a": "1", "b": "2"},
	}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		pb := &protogen.SpecRequest{
			ContainerId: src.ContainerID,
			Name:        src.Name,
			Spec:        src.Spec,
			Labels:      src.Labels,
		}
		data, err := proto.Marshal(pb)
		if err != nil {
			b.Fatal(err)
		}
		var got protogen.SpecRequest
		if err := proto.Unmarshal(data, &got); err != nil {
			b.Fatal(err)
		}
		out := &createspecv0.SpecRequest{
			ContainerID: got.GetContainerId(),
			Name:        got.GetName(),
			Spec:        got.GetSpec(),
			Labels:      got.GetLabels(),
		}
		_ = out
	}
}
