# reusable workflow
name: .test-prepare

# TODO: hide reusable workflow from the UI. Tracked in https://github.com/community/community/discussions/12025

on:
  workflow_call:
    outputs:
      matrix:
        description: Test matrix
        value: ${{ jobs.run.outputs.matrix }}

jobs:
  run:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - name: Create matrix
        id: set
        run: echo 'matrix=["graphdriver", "snapshotter"]' >> "$GITHUB_OUTPUT"
